### ISSUE TITLE
Server Testing

### ISSUE THREAD

**Issue by ShuaiKKKai** [UMM-CSci-3601-S18/iteration-1-hjakers#19]
This includes the controller spec file and JUnit testing. We should have some pretty good, solid testing going on here.

**Comment by corde171** [comment]
This name is somewhat confusing, given that the actual Server file consists of basically just a main method. Is this just me?

**Comment by john9hoff** [comment]
Yes, you are correct. The ItemControllerBasicSpec file has 100% coverage for the ItemController, so our JUnit testing should be done. I'm closing this. Apologies for not tagging this issue in my commits.
