### ISSUE TITLE
Embedded Images and Videos as Resources

### ISSUE THREAD

**Issue by john9hoff** [UMM-CSci-3601-S18/iteration-1-hjakers#23]
Users might like to see pictures or youtube videos that offer ways of coping with emotions, stress, etc.

**Comment by welch298** [comment]
I've figured out how to autoplay a video, only issue is figuring out the info of the video to put in the html

**Comment by welch298** [comment]
I fixed the issue I just commented about. As a note if you want a gif to play its considered an image, not a video as I had assumed

**Comment by john9hoff** [comment]
The embedded video does not look very good, moving to QA/Review.

**Comment by john9hoff** [comment]
We decided not to have a video, so closing.
